version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - sqlite-data:/app/data
      - uploads:/app/uploads
    environment:
      - DB_FILENAME=/app/data/wasatext.db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  sqlite-data:
  uploads: